{
  "channeldata": {
    "activate.d": false,
    "binary_prefix": false,
    "deactivate.d": false,
    "description": null,
    "dev_url": "https://github.com/LuminosoInsight/python-ftfy",
    "doc_source_url": null,
    "doc_url": "http://ftfy.readthedocs.io/",
    "home": "https://github.com/LuminosoInsight/python-ftfy/",
    "icon_hash": null,
    "icon_url": null,
    "identifiers": null,
    "keywords": null,
    "license": "MIT",
    "post_link": false,
    "pre_link": false,
    "pre_unlink": false,
    "recipe_origin": null,
    "run_exports": {},
    "source_git_url": null,
    "source_url": "https://pypi.io/packages/source/f/ftfy/ftfy-5.1.1.tar.gz",
    "subdirs": [
      "linux-64"
    ],
    "summary": "Fixes some problems with Unicode text after the fact",
    "tags": null,
    "text_prefix": true,
    "timestamp": 0,
    "version": "5.1.1"
  },
  "channeldata_version": 1,
  "feedstock": null,
  "labels": [
    "cf202003",
    "main"
  ],
  "package": "ftfy-5.1.1-py36_0.tar.bz2",
  "repodata": {
    "build": "py36_0",
    "build_number": 0,
    "depends": [
      "python 3.6*",
      "setuptools",
      "wcwidth"
    ],
    "license": "MIT",
    "md5": "8684a180fe0dcec7ede3140c06e8181d",
    "name": "ftfy",
    "sha256": "97346d418d1119ce9b0edabb29bf815ba0af766cfef506f5bc511f98deaeca67",
    "size": 50523,
    "subdir": "linux-64",
    "version": "5.1.1"
  },
  "repodata_version": 1,
  "subdir": "linux-64",
  "url": "https://conda.anaconda.org/conda-forge/linux-64/ftfy-5.1.1-py36_0.tar.bz2"
}