{
  "channeldata": {
    "activate.d": false,
    "binary_prefix": false,
    "deactivate.d": false,
    "description": null,
    "dev_url": null,
    "doc_source_url": null,
    "doc_url": null,
    "home": "https://github.com/pytest-dev/pytest-faulthandler",
    "icon_hash": null,
    "icon_url": null,
    "identifiers": null,
    "keywords": null,
    "license": "MIT",
    "post_link": false,
    "pre_link": false,
    "pre_unlink": false,
    "recipe_origin": null,
    "run_exports": {},
    "source_git_url": null,
    "source_url": "https://pypi.io/packages/source/p/pytest-faulthandler/pytest-faulthandler-1.6.0.tar.gz",
    "subdirs": [
      "linux-aarch64"
    ],
    "summary": "py.test plugin that activates the fault handler module for tests",
    "tags": null,
    "text_prefix": false,
    "timestamp": 1560568237,
    "version": "1.6.0"
  },
  "channeldata_version": 1,
  "feedstock": null,
  "labels": [
    "main",
    "cf202003"
  ],
  "package": "pytest-faulthandler-1.6.0-py37_0.tar.bz2",
  "repodata": {
    "build": "py37_0",
    "build_number": 0,
    "depends": [
      "pytest",
      "python >=3.7,<3.8.0a0"
    ],
    "license": "MIT",
    "md5": "f59248a719b5b7659d7b1ac8bab0ca27",
    "name": "pytest-faulthandler",
    "sha256": "7f48521b0174a08bd93073cf117b5ccdac8e0e5d4d7497faeaa49a3783ce301a",
    "size": 8069,
    "subdir": "linux-aarch64",
    "timestamp": 1560568237822,
    "version": "1.6.0"
  },
  "repodata_version": 1,
  "subdir": "linux-aarch64",
  "url": "https://conda.anaconda.org/conda-forge/linux-aarch64/pytest-faulthandler-1.6.0-py37_0.tar.bz2"
}