{
  "channeldata": {
    "activate.d": false,
    "binary_prefix": false,
    "deactivate.d": false,
    "description": null,
    "dev_url": null,
    "doc_source_url": null,
    "doc_url": null,
    "home": "https://github.com/utgwkk/pytest-github-actions-annotate-failures",
    "icon_hash": null,
    "icon_url": null,
    "identifiers": null,
    "keywords": null,
    "license": "MIT",
    "post_link": false,
    "pre_link": false,
    "pre_unlink": false,
    "recipe_origin": null,
    "run_exports": {},
    "source_git_url": null,
    "source_url": "https://pypi.io/packages/source/p/pytest-github-actions-annotate-failures/pytest-github-actions-annotate-failures-0.1.1.tar.gz",
    "subdirs": [
      "noarch"
    ],
    "summary": "pytest plugin to annotate failed tests with a workflow command for GitHub Actions",
    "tags": null,
    "text_prefix": false,
    "timestamp": 1602591922,
    "version": "0.1.1"
  },
  "channeldata_version": 1,
  "feedstock": "pytest-github-actions-annotate-failures-feedstock",
  "labels": [
    "main"
  ],
  "package": "pytest-github-actions-annotate-failures-0.1.1-pyh9f0ad1d_0.tar.bz2",
  "repodata": {
    "build": "pyh9f0ad1d_0",
    "build_number": 0,
    "depends": [
      "pytest >=4.0.0",
      "python"
    ],
    "license": "MIT",
    "md5": "86b26d93af60b01298ebc889888b2860",
    "name": "pytest-github-actions-annotate-failures",
    "noarch": "python",
    "sha256": "151dc578a947eb9d96a0756357e2bdc275c59c1ca2f40e13f0001640c57c1848",
    "size": 7629,
    "subdir": "noarch",
    "timestamp": 1602591922006,
    "version": "0.1.1"
  },
  "repodata_version": 1,
  "subdir": "noarch",
  "url": "https://github.com/regro/releases/releases/download/noarch/pytest-github-actions-annotate-failures-0.1.1-pyh9f0ad1d_0.tar.bz2/pytest-github-actions-annotate-failures-0.1.1-pyh9f0ad1d_0.tar.bz2"
}