{
  "channeldata": {
    "activate.d": false,
    "binary_prefix": false,
    "deactivate.d": false,
    "description": null,
    "dev_url": null,
    "doc_source_url": null,
    "doc_url": null,
    "home": "https://github.com/pytest-dev/pytest-faulthandler",
    "icon_hash": null,
    "icon_url": null,
    "identifiers": null,
    "keywords": null,
    "license": "MIT",
    "post_link": false,
    "pre_link": false,
    "pre_unlink": false,
    "recipe_origin": null,
    "run_exports": {},
    "source_git_url": null,
    "source_url": "https://pypi.io/packages/source/p/pytest-faulthandler/pytest-faulthandler-1.4.1.tar.gz",
    "subdirs": [
      "osx-64"
    ],
    "summary": "py.test plugin that activates the fault handler module for tests",
    "tags": null,
    "text_prefix": false,
    "timestamp": 0,
    "version": "1.4.1"
  },
  "channeldata_version": 1,
  "feedstock": null,
  "labels": [
    "main",
    "cf202003",
    "cf201901"
  ],
  "package": "pytest-faulthandler-1.4.1-py35_0.tar.bz2",
  "repodata": {
    "build": "py35_0",
    "build_number": 0,
    "depends": [
      "pytest",
      "python 3.5*"
    ],
    "license": "MIT",
    "md5": "5d7e60368780061daf59e913d86bbe97",
    "name": "pytest-faulthandler",
    "sha256": "0eee78045c6751f6032fcd8996f158e6789a9385403da3902e42e6e44f3a4729",
    "size": 8448,
    "subdir": "osx-64",
    "version": "1.4.1"
  },
  "repodata_version": 1,
  "subdir": "osx-64",
  "url": "https://conda.anaconda.org/conda-forge/osx-64/pytest-faulthandler-1.4.1-py35_0.tar.bz2"
}