{
  "channeldata": {
    "activate.d": false,
    "binary_prefix": false,
    "deactivate.d": false,
    "description": null,
    "dev_url": null,
    "doc_source_url": null,
    "doc_url": null,
    "home": "https://github.com/thedataincubator/expectexception",
    "icon_hash": null,
    "icon_url": null,
    "identifiers": null,
    "keywords": null,
    "license": "BSD-3-Clause",
    "post_link": false,
    "pre_link": false,
    "pre_unlink": false,
    "recipe_origin": null,
    "run_exports": {},
    "source_git_url": null,
    "source_url": "https://pypi.io/packages/source/e/expectexception/ExpectException-0.1.1.tar.gz",
    "subdirs": [
      "noarch"
    ],
    "summary": "Jupyter magic for exceptions",
    "tags": null,
    "text_prefix": false,
    "timestamp": 1634317242,
    "version": "0.1.1"
  },
  "channeldata_version": 1,
  "feedstock": "expectexception-feedstock",
  "labels": [
    "main"
  ],
  "package": "expectexception-0.1.1-pyhd8ed1ab_0.tar.bz2",
  "repodata": {
    "build": "pyhd8ed1ab_0",
    "build_number": 0,
    "depends": [
      "ipython",
      "python >=3.6"
    ],
    "license": "BSD-3-Clause",
    "md5": "db2a4e7998cb6ada9e9abc7905f43589",
    "name": "expectexception",
    "noarch": "python",
    "sha256": "44b703d6c694dd62bc3bffb2244d5eb2baa26c57949c97bab676873f09c03c6a",
    "size": 7078,
    "subdir": "noarch",
    "timestamp": 1634317242969,
    "version": "0.1.1"
  },
  "repodata_version": 1,
  "subdir": "noarch",
  "url": "https://github.com/conda-forge/releases/releases/download/noarch/expectexception-0.1.1-pyhd8ed1ab_0.tar.bz2/expectexception-0.1.1-pyhd8ed1ab_0.tar.bz2"
}