{
  "channeldata": {
    "activate.d": false,
    "binary_prefix": false,
    "deactivate.d": false,
    "description": null,
    "dev_url": null,
    "doc_source_url": null,
    "doc_url": null,
    "home": "https://github.com/benkehoe/aws-error-utils",
    "icon_hash": null,
    "icon_url": null,
    "identifiers": null,
    "keywords": null,
    "license": "Apache-2.0",
    "post_link": false,
    "pre_link": false,
    "pre_unlink": false,
    "recipe_origin": null,
    "run_exports": {},
    "source_git_url": null,
    "source_url": "https://pypi.io/packages/source/a/aws-error-utils/aws-error-utils-1.2.0.tar.gz",
    "subdirs": [
      "noarch"
    ],
    "summary": "Error-handling functions for boto3/botocore",
    "tags": null,
    "text_prefix": false,
    "timestamp": 1630518008,
    "version": "1.2.0"
  },
  "channeldata_version": 1,
  "feedstock": "aws-error-utils-feedstock",
  "labels": [
    "main"
  ],
  "package": "aws-error-utils-1.2.0-pyhd8ed1ab_0.tar.bz2",
  "repodata": {
    "build": "pyhd8ed1ab_0",
    "build_number": 0,
    "depends": [
      "botocore",
      "python !=3.0,!=3.1,!=3.2"
    ],
    "license": "Apache-2.0",
    "md5": "3383801ea01a92a29ea9d38cb149c9cd",
    "name": "aws-error-utils",
    "noarch": "python",
    "sha256": "ca94a6d2a724c59b90abc7840afddf2ffd4fd6c41e5f21a55f039ebc72590917",
    "size": 13872,
    "subdir": "noarch",
    "timestamp": 1630518008128,
    "version": "1.2.0"
  },
  "repodata_version": 1,
  "subdir": "noarch",
  "url": "https://github.com/conda-forge/releases/releases/download/noarch/aws-error-utils-1.2.0-pyhd8ed1ab_0.tar.bz2/aws-error-utils-1.2.0-pyhd8ed1ab_0.tar.bz2"
}