{
  "channeldata": {
    "activate.d": false,
    "binary_prefix": false,
    "deactivate.d": false,
    "description": null,
    "dev_url": null,
    "doc_source_url": null,
    "doc_url": null,
    "home": "https://github.com/pytest-dev/pytest-faulthandler",
    "icon_hash": null,
    "icon_url": null,
    "identifiers": null,
    "keywords": null,
    "license": "MIT",
    "post_link": false,
    "pre_link": false,
    "pre_unlink": false,
    "recipe_origin": null,
    "run_exports": {},
    "source_git_url": null,
    "source_url": "https://pypi.io/packages/source/p/pytest-faulthandler/pytest-faulthandler-1.4.1.tar.gz",
    "subdirs": [
      "linux-64"
    ],
    "summary": "py.test plugin that activates the fault handler module for tests",
    "tags": null,
    "text_prefix": false,
    "timestamp": 0,
    "version": "1.4.1"
  },
  "channeldata_version": 1,
  "feedstock": null,
  "labels": [
    "main",
    "cf202003",
    "cf201901"
  ],
  "package": "pytest-faulthandler-1.4.1-py36_0.tar.bz2",
  "repodata": {
    "build": "py36_0",
    "build_number": 0,
    "depends": [
      "pytest",
      "python 3.6*"
    ],
    "license": "MIT",
    "md5": "b406af0198062cb27c05000eb9dc4cc9",
    "name": "pytest-faulthandler",
    "sha256": "75cbbe99653f0976d46426dce87a4802bacf0b0c6ca0ca94ebbd259be6c76ba9",
    "size": 8206,
    "subdir": "linux-64",
    "version": "1.4.1"
  },
  "repodata_version": 1,
  "subdir": "linux-64",
  "url": "https://github.com/regro/releases/releases/download/linux-64/pytest-faulthandler-1.4.1-py36_0.tar.bz2/pytest-faulthandler-1.4.1-py36_0.tar.bz2"
}