{
  "channeldata": {
    "activate.d": false,
    "binary_prefix": false,
    "deactivate.d": false,
    "description": null,
    "dev_url": null,
    "doc_source_url": null,
    "doc_url": null,
    "home": "https://github.com/utgwkk/pytest-github-actions-annotate-failures",
    "icon_hash": null,
    "icon_url": null,
    "identifiers": null,
    "keywords": null,
    "license": "MIT",
    "post_link": false,
    "pre_link": false,
    "pre_unlink": false,
    "recipe_origin": null,
    "run_exports": {},
    "source_git_url": null,
    "source_url": "https://pypi.io/packages/source/p/pytest-github-actions-annotate-failures/pytest-github-actions-annotate-failures-0.1.6.tar.gz",
    "subdirs": [
      "noarch"
    ],
    "summary": "pytest plugin to annotate failed tests with a workflow command for GitHub Actions",
    "tags": null,
    "text_prefix": false,
    "timestamp": 1638975361,
    "version": "0.1.6"
  },
  "channeldata_version": 1,
  "feedstock": "pytest-github-actions-annotate-failures-feedstock",
  "labels": [
    "main"
  ],
  "package": "pytest-github-actions-annotate-failures-0.1.6-pyhd8ed1ab_0.tar.bz2",
  "repodata": {
    "build": "pyhd8ed1ab_0",
    "build_number": 0,
    "depends": [
      "pytest >=4.0.0",
      "python 2.7|>=3.6"
    ],
    "license": "MIT",
    "md5": "247ea749fb420c063be7c3e7020592aa",
    "name": "pytest-github-actions-annotate-failures",
    "noarch": "python",
    "sha256": "1adbf243ec2617e9719beb9b3ca1f59d6684d95ae935c30ebf797bf0ab7ab68b",
    "size": 8378,
    "subdir": "noarch",
    "timestamp": 1638975361332,
    "version": "0.1.6"
  },
  "repodata_version": 1,
  "subdir": "noarch",
  "url": "https://github.com/conda-forge/releases/releases/download/noarch/pytest-github-actions-annotate-failures-0.1.6-pyhd8ed1ab_0.tar.bz2/pytest-github-actions-annotate-failures-0.1.6-pyhd8ed1ab_0.tar.bz2"
}