{
  "channeldata": {
    "activate.d": false,
    "binary_prefix": false,
    "deactivate.d": false,
    "description": null,
    "dev_url": null,
    "doc_source_url": null,
    "doc_url": null,
    "home": "https://github.com/yashtodi94/pytest-custom_exit_code",
    "icon_hash": null,
    "icon_url": null,
    "identifiers": null,
    "keywords": null,
    "license": "MIT",
    "post_link": false,
    "pre_link": false,
    "pre_unlink": false,
    "recipe_origin": null,
    "run_exports": {},
    "source_git_url": null,
    "source_url": "https://pypi.io/packages/source/p/pytest-custom-exit-code/pytest-custom_exit_code-0.3.0.tar.gz",
    "subdirs": [
      "noarch"
    ],
    "summary": "Exit pytest test session with custom exit code in different scenarios",
    "tags": null,
    "text_prefix": false,
    "timestamp": 1565965567,
    "version": "0.3.0"
  },
  "channeldata_version": 1,
  "feedstock": null,
  "labels": [
    "main"
  ],
  "package": "pytest-custom-exit-code-0.3.0-py_0.tar.bz2",
  "repodata": {
    "build": "py_0",
    "build_number": 0,
    "depends": [
      "pytest >=4.0.2",
      "python"
    ],
    "license": "MIT",
    "license_family": "MIT",
    "md5": "8389a05ed425559b88ad2af1f92b7c08",
    "name": "pytest-custom-exit-code",
    "noarch": "python",
    "sha256": "e7a7df4ce83b15e901ba7e9850fc45195de95004adfdda91bdb331b7e516fc60",
    "size": 6645,
    "subdir": "noarch",
    "timestamp": 1565965567103,
    "version": "0.3.0"
  },
  "repodata_version": 1,
  "subdir": "noarch",
  "url": "https://conda.anaconda.org/conda-forge/noarch/pytest-custom-exit-code-0.3.0-py_0.tar.bz2"
}