{
  "channeldata": {
    "activate.d": false,
    "binary_prefix": false,
    "deactivate.d": false,
    "description": null,
    "dev_url": null,
    "doc_source_url": null,
    "doc_url": null,
    "home": "https://github.com/pytest-dev/pytest-faulthandler",
    "icon_hash": null,
    "icon_url": null,
    "identifiers": null,
    "keywords": null,
    "license": "MIT",
    "post_link": false,
    "pre_link": false,
    "pre_unlink": false,
    "recipe_origin": null,
    "run_exports": {},
    "source_git_url": null,
    "source_url": "https://pypi.io/packages/source/p/pytest-faulthandler/pytest-faulthandler-2.0.1.tar.gz",
    "subdirs": [
      "linux-64"
    ],
    "summary": "py.test plugin that activates the fault handler module for tests (dummy package now)",
    "tags": null,
    "text_prefix": false,
    "timestamp": 1562279197,
    "version": "1.3.0"
  },
  "channeldata_version": 1,
  "feedstock": null,
  "labels": [
    "main"
  ],
  "package": "pytest-faulthandler-1.3.0-py27_0.tar.bz2",
  "repodata": {
    "arch": "x86_64",
    "build": "py27_0",
    "build_number": 0,
    "constrains": [
      "python_abi * *_cp27mu"
    ],
    "depends": [
      "pytest",
      "python 2.7*"
    ],
    "license": "MIT",
    "license_family": "MIT",
    "md5": "7a13b561c1e6f04a0f3e096091c3fc84",
    "name": "pytest-faulthandler",
    "platform": "linux",
    "sha256": "d45f711f8c67f6cfb410dfa90952157c91099f56a03a21adbc61364e32fc0418",
    "size": 4299,
    "subdir": "linux-64",
    "version": "1.3.0"
  },
  "repodata_version": 1,
  "subdir": "linux-64",
  "url": "https://conda.anaconda.org/conda-forge/linux-64/pytest-faulthandler-1.3.0-py27_0.tar.bz2"
}